version: '3'
services:
  waardepapieren-service:
    build: waardepapieren-service/.
    ports:
      - 3232:3232
      - 3233:3233
    environment:
      - NLX_OUTWAY_ENDPOINT=http://localhost:4080
  clerk-frontend:
    build: clerk-frontend/
    links:
      - waardepapieren-service
    ports:
      - 8080:8080
