version: '3'
services:
  waardepapieren-service:
    volumes:
    - ./waardepapieren-service/system-test/certs:/certs:ro
    build: waardepapieren-service/.
    links:
      - mock-nlx
    ports:
      - 3232:3232
      - 3233:3233
    environment:
      - NLX_OUTWAY_ENDPOINT=http://mock-nlx:80
  clerk-frontend:
    build: clerk-frontend/
    links:
      - waardepapieren-service
    ports:
      - 8080:8080
    healthcheck:
      test: service nginx status
  mock-nlx:
    image: nlxio/outway:latest
    volumes:
      - ./waardepapieren-service/system-test/certs:/certs:ro
    environment:
      - DIRECTORY_INSPECTION_ADDRESS=directory-inspection-api.demo.nlx.io:443
      - TLS_NLX_ROOT_CERT=/certs/root.crt
      - TLS_ORG_CERT=/certs/org.crt
      - TLS_ORG_KEY=/certs/org.key
      - DISABLE_LOGDB=1
    ports:
      - 4080:80
